"""
Django settings for social_media_api project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-68x2sdmz=%u!xpo-(pej5khrrsi3gsvd&aix&yylw-^$1@_04j'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False  # Week 15 - Task 4 - step 1_1 - Update settings.py for Production ppty

ALLOWED_HOSTS = ['yourdomain.com', 'www.yourdomain.com', 'your_ip_address'] # Week 15 - Task 4 - step 1_1 - Update settings.py for Production ppty


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework', # Add Django REST Framework - Week 15 - Task 0 - step 1_5 - Configure settings.py </> Add Installed Apps
    'rest_framework.authtoken',  # Add token authentication
    'accounts', # Add accounts app for user management
    'posts', # Add posts app for comment and posting
    'notifications' # Add notifications app for notifications
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # Week 15 - Task 4 - step 1_3 - Static Files Configuration ppty
]

ROOT_URLCONF = 'social_media_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'social_media_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'USER': 'your_db_user', # Week 15 - Task 4 - step 1_1 - Update settings.py for Production ppty
        'PASSWORD': 'your_db_password',
        'HOST': 'localhost',  # or your database host
        'PORT': '',  # default is usually fine
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/' # Week 15 - Task 4 - step 1_3 - Static Files Configuration ppty changed from 'static/' to '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # Week 15 - Task 4 - step 1_3 - Static Files Configuration ppty (Ensure this directory exists)

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Week 15 - Task 0 - step 2_2 - Update Settings to specify the Custom User Model
AUTH_USER_MODEL = 'accounts.CustomUser'


# Week 15 - Task 1 - step 5_1 - Implement Pagination and Filtering
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10
}

# Week 15 - Task 4 - step 1_1 - Update settings.py for Production ppty

SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_SSL_REDIRECT = True  # Redirect all HTTP requests to HTTPS